CREATE TABLE games (
    id TEXT UNIQUE NOT NULL PRIMARY KEY,
    teamA INTEGER NOT NULL,
    teamB INTEGER NOT NULL,
    score_change INTEGER,
    created BIGINT NOT NULL DEFAULT extract(epoch from CURRENT_TIMESTAMP)
)