// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Bot { id: number, team: number, name: string, description: string | null, score: number, created: bigint, uploaded_by: string, build_status: number, }