// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhichBot } from "./WhichBot";

export type GameError = { RunTimeError: WhichBot } | { TimeoutError: WhichBot } | { MemoryError: WhichBot } | { InvalidActionError: WhichBot } | "InternalError";