// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface User { email: string, display_name: string, team_id: number | null, is_admin: boolean, }