// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { CommunityCards } from "./CommunityCards";
import type { EndReason } from "./EndReason";
import type { HoleCards } from "./HoleCards";
import type { PlayerPosition } from "./PlayerPosition";
import type { WhichBot } from "./WhichBot";

export interface GameStateSQL { game_id: string, step: number, challenger_stack: number, defender_stack: number, challenger_pushed: number, defender_pushed: number, challenger_hand: HoleCards, defender_hand: HoleCards, community_cards: CommunityCards, sb: WhichBot, action_time: number, whose_turn: PlayerPosition | null, action_val: Action, end_reason: EndReason | null, }