// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AnonymousUser { display_name: string, team: number | null, email_hash: string, }