// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotWithTeam } from "./BotWithTeam";
import type { Team } from "./Team";

export type BotsResponse = { "Count": bigint } | { "Bots": Array<BotWithTeam<Team>> };