// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bot } from "./Bot";
import type { BotWithTeam } from "./BotWithTeam";
import type { Team } from "./Team";

export type BotsResponse = { Count: bigint } | { Bots: Array<Bot> } | { BotsWithTeam: Array<BotWithTeam<Team>> };