// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildStatus } from "./BuildStatus";
import type { User } from "./User";

export interface BotWithTeam<T> { id: number, team: T, name: string, description: string | null, created: bigint, uploaded_by: User, build_status: BuildStatus, }