// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameResult } from "./GameResult";

export interface GameWithResult { id: string, defender: number, challenger: number, created: bigint, defender_rating: number, challenger_rating: number, result: GameResult | null, rated: boolean, }