// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BotWithTeam } from "./BotWithTeam";
import type { Game } from "./Game";
import type { GameWithBots } from "./GameWithBots";
import type { Team } from "./Team";

export type GamesResponse = { Count: bigint } | { Games: Array<Game> } | { GamesWithBots: Array<GameWithBots<BotWithTeam<Team>>> };