// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameResult } from "./GameResult";

export interface GameWithBotsWithResult<T> { id: string, defender: T, challenger: T, created: bigint, defender_rating: number, challenger_rating: number, result: GameResult | null, }