// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Game { id: string, defender: number, challenger: number, score_change: number | null, created: bigint, error_type: string | null, error_message: string | null, }