// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GameQueryOptions { id: string | null, team: number | null, running: boolean | null, }