// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhichBot } from "./WhichBot";

export interface GameWithBots<T> { id: string, defender: T, challenger: T, defender_score: number | null, challenger_score: number | null, created: bigint, error_type: string | null, error_bot: WhichBot | null, }