// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GameStateSQL {
  game_id: string;
  step: number;
  defender_stack: number;
  challenger_stack: number;
  defender_pushed: number;
  challenger_pushed: number;
  defender_hand: string;
  challenger_hand: string;
  flop: string | null;
  turn: string | null;
  river: string | null;
  button: string;
  sb: string;
  action_time: number;
  last_action: string;
}
