// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GameResult { id: string, challenger_rating_change: number, defender_rating_change: number, defender_score: number, challenger_score: number, error_type: string | null, error_bot: number | null, updated_at: bigint, }