// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Game { id: string, defender: number, challenger: number, defender_score: number | null, challenger_score: number | null, created: bigint, error_type: string | null, error_bot: number | null, }