// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamInvite } from "./TeamInvite";

export interface TeamWithMembers<T> { id: number, name: string, owner: string, score: number | null, active_bot: number | null, members: Array<T>, invites: Array<TeamInvite> | null, deleted_at: bigint | null, }