// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserProfile { first_name: string, last_name: string, country: string | null, school: string, linkedin: string | null, github: string | null, resume_s3_key: string | null, id: string, }